### PR TITLE
adding maxython to donate.md

### PR DESCRIPTION
**Pull request by Maxython**
Question: the description that I wrote is similar to what I really do?

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Looks fine other than commit message.

**Comment by Maxython** [comment]
Better?

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux.github.io/commits/master and https://github.com/termux/termux-app#for-maintainers-and-contributors

If you want to add `donate` scope, it must be inside round brackets.

**Comment by Maxython** [comment]
> Check https://github.com/termux/termux.github.io/commits/master and https://github.com/termux/termux-app#for-maintainers-and-contributors
> 
> If you want to add `donate` scope, it must be inside round brackets.

Ok, thank.

**Comment by Maxython** [comment]
Approximately like this?

**Comment by agnostic-apollo** [comment]
Closed with c6f4be72

**Pull request closed without merging**
